TypeError when using multiple pens for different lines (#2704)
* Update GraphItem.py

comparison with None will always cause 
```
if np.any(pen != lastPen):
TypeError: Cannot compare structured or void to non-void arrays.
```
This does not really follow DRY principle but was the best solution I could come up with using static types in structured array

* fix for multiple different pens